ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.bank.SerializationKt.configureSerialization
      - com.bank.LedgerKt.configureLedger
      - com.bank.RoutingKt.configureRouting
